version: "3.8"
services:
  server:
    build: .
    container_name: apple-healt-server
    ports:
      - "38001:38001"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: timescale/timescaledb-postgis:latest-pg13
    container_name: apple-health-db
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "35432:5432"

  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: apple-health-grafana
    ports:
      - "33000:3000"
    depends_on:
      - server
    volumes: # chown 472:472 grafana -R
      - ./grafana:/data
    env_file:
      - .env
    environment:
      - GF_DEFAULT_INSTANCE_NAME=health-export
      - GF_LOG_MODE=console
      - GF_PATHS_DATA=/data
      - PORT=3000
